## CI - Upload packages to NPM
name: Upload packages to NPM and S3
run-name: Upload packages to NPM and S3

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  upload-packages-to-npm:
    uses: ./.github/workflows/upload_to_npm.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      prod: "false"
  upload-to-s3-qa-and-dev:
    needs: upload-packages-to-npm
    uses: ./.github/workflows/upload_to_s3.yaml
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
    with:
      aws-secret-central: '"dor-test-github-actions"'
      kind: "plugin"
      prod: "false"
