### CI - Player Tests
#name: Player Tests
#
#on:
#  pull_request:
#    branches:
#      - devops-pr
#
#jobs:
#  running-tests:
#    uses: kaltura/playkit-js-youbora/.github/workflows/run_player_tests.yml@devops-tests
#    with:
#      yarn-run-to-execute: 'eslint flow'
#
