### CI - Release Version
#name: Release Version QA
#
#on:
#  pull_request:
#    branches:
#      - devops-pr
#
#jobs:
#  release-version-qa:
#    uses: kaltura/playkit-js-youbora/.github/workflows/upload_packages_npm.yaml@devops-tests
#    secrets:
#      NPM_JFROG_USER: ${{ secrets.NPM_JFROG_USER }}
#      NPM_JFROG_PASS: ${{ secrets.NPM_JFROG_PASS }}
#    with:
#      yarn-run-to-execute: '"release"'
#      npm-registry-url: 'https://kalturaa.jfrog.io/artifactory/api/npm/dor-test-nodejs-virtual/'
#
