## CI - Run Tests
name: Run Tests

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  running-tests:
    uses: kaltura/ovp-pipelines/.github/workflows/player_run_tests.yml@player-workflows
    with:
      yarn-run-to-execute: [eslint, flow]

