## CI - Run Tests
name: Run Tests

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  running-tests:
    uses: kaltura/ovp-pipelines/.github/workflows/player_run_tests.yml@6e5a277456a01d3cf0fe46399f65cbe92fb61502
    with:
      yarn-run-to-execute: "[eslint, flow]"


