## CI - Upload packages to NPM
name: Upload packages to NPM and S3
run-name: Upload packages to NPM and S3

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  upload-packages-to-npm:
    uses: ./.github/workflows/upload_to_npm.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      prod: "false"
  upload-to-s3-qa-and-dev:
    needs: upload-packages-to-npm
    uses: ./.github/workflows/upload_to_s3.yaml
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
    with:
      aws-secret-central: "github-aws-dev-qa-accounts-8iI9eS"
      type: "plugin"
      name: ${{ needs.upload-packages-to-npm.outputs.name }}
      version: ${{ needs.upload-packages-to-npm.outputs.version }}
      full-npm-name: ${{ needs.upload-packages-to-npm.outputs.full-npm-name }}
  update-schema:
    needs: [upload-to-s3-qa-and-dev, upload-packages-to-npm]
    uses: ./.github/workflows/update_schema.yaml
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      SERVICES_ACCOUNT_ID: ${{ secrets.SERVICES_ACCOUNT_ID }}
      S3_BUCKET_DEPLOYMENT: ${{ secrets.S3_BUCKET_DEPLOYMENT }}
    with:
      prod: "false"
      type: "plugin"
      schema-type: "playerV3Versions"
      name: ${{ needs.upload-packages-to-npm.outputs.name }}
      version: ${{ needs.upload-packages-to-npm.outputs.version }}
  build-uiconf:
    needs: [update-schema, upload-to-s3-qa-and-dev, upload-packages-to-npm]
    uses: ./.github/workflows/build_uiconf.yaml
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      SERVICES_ACCOUNT_ID: ${{ secrets.SERVICES_ACCOUNT_ID }}
      S3_BUCKET_DEPLOYMENT: ${{ secrets.S3_BUCKET_DEPLOYMENT }}
    with:
      stage: "canary"
      schema-type: "playerV3Versions"
  deploy-uiconf:
    needs: [ build-uiconf, update-schema, upload-to-s3-qa-and-dev, upload-packages-to-npm ]
    uses: ./.github/workflows/deploy_uiconf.yaml
    secrets:
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
    with:
      stage: "canary"
      version: ${{ needs.build-uiconf.outputs.version }}
      schema-type: "playerV3Versions"

