## CI - Release Version
name: Upload to s3 QA

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  upload-to-s3-qa:
    uses: kaltura/playkit-js-youbora/.github/workflows/upload_to_s3.yaml@devops-tests
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
    with:
      aws-secret-central: '"dor-test-github-actions"'
