name: Check notification

on:
  push:
    branches:
      - devops-deployment

jobs:
  without_optional_params:
    name: One with little info
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
