## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests by

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  running-tests:
    uses: ./.github/workflows/tests.yaml
    with:
      yarn-run-to-execute: 'eslint flow'


