name: Check notification

on:
  push:
    branches:
      - devops-deployment

jobs:
  without_optional_params:
    name: One with little info
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@v1.0.4
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "title": "No ${variables} avaliable in here"
            }
