name: Run Tests
on:
  pull_request:
    branches:
      - devops-pr

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Testing on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-firefox@v1
      - run: chrome --version
      - run: firefox --version
#      - run: yarn install
#      - run: yarn run eslint
#      - run: yarn run flow
#      - run: yarn run test
#        env:
#          NODE_OPTIONS: '--openssl-legacy-provider'

