name: Run Tests
on:
  pull_request:
    branches:
      - devops-pr

jobs:
  tests:
    env:
      NODE_OPTIONS: '--openssl-legacy-provider'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Testing on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run eslint
      - run: yarn run flow
      - run: yarn run test

