## CI - Upload packages to NPM
name: Upload packages to NPM and S3
run-name: Upload packages to NPM and S3

on:
  push:
    branches:
      - devops-pr

jobs:
  running-tests:
    uses: ./.github/workflows/tests.yaml
    with:
      yarn-run-to-execute: 'eslint flow'
  upload-packages-to-npm:
    uses: ./.github/workflows/upload_to_npm.yaml
    secrets:
      NPM_JFROG_USER: ${{ secrets.NPM_JFROG_USER }}
      NPM_JFROG_PASS: ${{ secrets.NPM_JFROG_PASS }}
    with:
      yarn-run-to-execute: '"release"'
      npm-registry-url: 'https://kalturaa.jfrog.io/artifactory/api/npm/dor-test-nodejs-virtual/'
  upload-to-s3-qa-and-dev:
    uses: ./.github/workflows/upload_to_s3.yaml
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
    with:
      aws-secret-central: '"dor-test-github-actions"'
      kind: "plugin"
