## CI - Upload packages to NPM
name: Upload packages to NPM
run-name: Upload packages to NPM by @${{ github.actor }}

on:
  pull_request:
    branches:
      - devops-pr

jobs:
  upload-packages-to-npm:
    uses: kaltura/playkit-js-youbora/.github/workflows/upload_packages_npm.yaml@devops-tests
    secrets:
      NPM_JFROG_USER: ${{ secrets.NPM_JFROG_USER }}
      NPM_JFROG_PASS: ${{ secrets.NPM_JFROG_PASS }}
    with:
      yarn-run-to-execute: '"release"'
      npm-registry-url: 'https://kalturaa.jfrog.io/artifactory/api/npm/dor-test-nodejs-virtual/'

