name: Player And Plugin Release Version QA
on:
  workflow_call:
    secrets:
      CENTRAL_ACCOUNT_ID:
        required: true
      S3_BUCKET_APPS:
        required: true
    inputs:
      aws-secret-central:
        description: "secret in central that include all the account ids"
        required: true
        type: string

jobs:
  upload-to-s3-qa:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [ 17.x ]
        test-map: [   {     env: nvd1,     account_id: 515842265945,     region: us-east-1   },   {     env: nvq1,     account_id: 383697330906,     region: us-east-1   } ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: test map
        run: |
          echo "env: ${{ matrix.test-map.env }}, account_id: ${{ matrix.test-map.account_id }}, region: ${{ matrix.test-map.region }} "
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CENTRAL_ACCOUNT_ID }}:role/dor-test-oidc-github-actions
          role-session-name: githubAction
          aws-region: "us-east-1"
      - name: List s3
        run: aws s3 ls s3://nvd1-${{ secrets.S3_BUCKET_APPS }}/

