name: Player And Plugin Release Version QA
on:
  workflow_call:
    inputs:
      yarn-run-to-execute:
        description: "list of package.json scripts - example: 'eslint flow test'"
        required: true
        type: string
      npm-registry-url:
        description: "npm registry url - example: 'https://kalturaa.jfrog.io/artifactory/api/npm/dor-test-nodejs-virtual/'"
        required: true
        type: string

jobs:
  release-version-qa:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [ 17.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ inputs.npm-registry-url }}
          JF_ACCESS_TOKEN: ${{ secrets.NPM_JFROG_TOKEN }}
      - run: |
          jf rt ping


