name: Player And Plugin Release Version QA
on:
  workflow_call:
    secrets:
      CENTRAL_ACCOUNT_ID:
        required: true
      S3_BUCKET_APPS:
        required: true
    inputs:
      aws-secret-central:
        description: "secret in central that include all the account ids"
        required: true
        type: string

jobs:
  get-accounts:
    strategy:
      matrix:
        test: '{"include":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.project }}
      - run: echo ${{ matrix.config }}


