## CI - Upload to s3 QA and Dev
name: Upload to s3 QA and Dev
run-name: Upload to s3 QA and Dev by @${{ github.actor }}

on:
  push:
    branches:
      - devops-pr

jobs:
  upload-to-s3-qa-and-dev:
    uses: kaltura/playkit-js-youbora/.github/workflows/upload_to_s3.yaml@devops-tests
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
    with:
      aws-secret-central: '"dor-test-github-actions"'
      kind: "plugin"



