name: Upload to s3 QA and Dev
run-name: Upload to s3 QA and Dev

on:
  workflow_call:
    secrets:
      CENTRAL_ACCOUNT_ID:
        required: true
      S3_BUCKET_APPS:
        required: true
    inputs:
      aws-secret-central:
        description: "secret in central that include all the account ids"
        required: true
        type: string
      kind:
        description: "choose player or plugin - example: 'plugin'"
        required: true
        type: string
      full-npm-name:
        description: "name package with version example: '@playkit-js/xxx@xxx'"
        required: true
        type: string
      version:
        description: "name example: '@playkit-js/xxx@xxx'"
        required: true
        type: string
      name:
        description: "name package with version example: '@playkit-js/xxx@xxx'"
        required: true
        type: string

env:
  PLAYERS: "ovp tv"

jobs:
  get-accounts:
    runs-on: [ubuntu-latest]
    steps:
      - name: Get environments list
        run: |
          echo "${{ inputs.version }}"
          echo "${{ inputs.name }}"
          echo "${{ inputs.full-npm-name }}"

