## CI - Upload packages to NPM
name: Upload packages to NPM
run-name: Upload packages to NPM by @${{ github.actor }}

on:
  push:
    branches:
      - devops-pr

jobs:
  release-version-qa:
    uses: kaltura/playkit-js-youbora/.github/workflows/upload_packages_npm.yaml@devops-tests
    secrets:
      NPM_JFROG_USER: ${{ secrets.NPM_JFROG_USER }}
      NPM_JFROG_PASS: ${{ secrets.NPM_JFROG_PASS }}
    with:
      yarn-run-to-execute: '"release"'
      npm-registry-url: 'https://kalturaa.jfrog.io/artifactory/api/npm/dor-test-nodejs-virtual/'

