## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  notification:
    if: always()
    uses: ./.github/workflows/test_webhook.yaml
    secrets:
      MSTEAMS_WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}


